---
openapi: 3.0.3
info:
  title: multiplication-service API
  version: 1.0-SNAPSHOT
paths:
  /:
    post:
      tags:
      - Operation Resource
      operationId: multiply
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultiplicationOperation'
      responses:
        "200":
          description: MultiplicationResult
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    MultiplicationOperation:
      type: object
      properties:
        leftElement:
          format: float
          type: number
        rightElement:
          format: float
          type: number
    Result:
      type: object
      properties:
        product:
          format: float
          type: number
