apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: event-display
  name: event-display
spec:
  template:
    metadata:
      annotations:
        # Keep always one instance to facilitate the events visualization.
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
      labels:
        app.kubernetes.io/name: event-display
    spec:
      containers:
        - # This corresponds to
          # https://github.com/knative/eventing-contrib/tree/main/cmd/event_display
          image: gcr.io/knative-releases/knative.dev/eventing-contrib/cmd/event_display@sha256:a214514d6ba674d7393ec8448dd272472b2956207acb3f83152d3071f0ab1911
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-event-display
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display